# Cluster Link
cluster.link.enabled=true
cluster.link.autodetect.address=

# TCP unicast JGroups
cluster.link.channel.properties.control=/opt/liferay/unicast/tcp.xml
cluster.link.channel.properties.transport.0=/opt/liferay/unicast/tcp.xml

# X.509 Security (se você quer segurança)
cluster.link.auth.cert.alias=liferay-node1-cert
cluster.link.auth.cert.password=TESTE$%3030
cluster.link.auth.cipher.type=RSA
cluster.link.auth.keystore.password=TESTE$%3030
cluster.link.auth.keystore.path=/opt/liferay/unicast/cluster_link_keystore.jks
cluster.link.auth.keystore.type=JKS
cluster.link.auth.value=TESTE$%3030

# Para ver terminal de logs identificando nó
web.server.display.node=true
