cluster.link.enabled=true
cluster.link.autodetect.address=postgres:5432
cluster.link.channel.properties.control=jgroups/secure/x509/udp_control.xml
cluster.link.channel.properties.transport.0=jgroups/secure/x509/udp_transport.xml
cluster.link.auth.cert.alias=liferay-node1-cert
cluster.link.auth.cert.password=TESTE$%3030
cluster.link.auth.cipher.type=RSA
cluster.link.auth.keystore.password=TESTE$%3030
cluster.link.auth.keystore.path=/opt/liferay/cluster_link_keystore.jks
cluster.link.auth.keystore.type=JKS
cluster.link.auth.value=TESTE$%3030

web.server.display.node=true